#!/usr/bin/env python3
"""
Generates bip39_wordlist.h from the official BIP39 English wordlist.

Usage:
    python3 generate_wordlist.py english.txt bip39_wordlist.h

Get english.txt from the official source:
    https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
(Save the raw file locally - one word per line, 2048 lines total.)

The script verifies the list is the correct length and spot-checks the
first/last words against the spec before writing the header, so a
truncated or corrupted download will fail loudly instead of silently
producing a broken wordlist.

Output format: all 2048 words are packed back-to-back into a single
PROGMEM byte blob, each terminated by a null byte, in official wordlist
order - no per-word array + pointer table. On an ATmega328P (32KB flash)
a 2048-entry pointer table alone costs 4KB, which doesn't fit alongside
the OLED library and app logic. Word N is found at runtime by skipping
N null-terminated strings from the start of the blob (see
getWordAtIndex() in the main sketch) - O(N) instead of O(1), but this
runs at most 24 times per generated seed phrase, so the cost is trivial.
"""

import sys

WORDS_PER_LINE = 8

def main():
    if len(sys.argv) != 3:
        print("Usage: python3 generate_wordlist.py <english.txt> <bip39_wordlist.h>")
        sys.exit(1)

    src_path, out_path = sys.argv[1], sys.argv[2]

    with open(src_path, "r", encoding="utf-8") as f:
        words = [line.strip() for line in f if line.strip()]

    if len(words) != 2048:
        print(f"ERROR: expected 2048 words, got {len(words)}. Check your source file.")
        sys.exit(1)
    if words[0] != "abandon" or words[-1] != "zoo":
        print("ERROR: wordlist doesn't match the expected BIP39 English list "
              f"(first='{words[0]}', last='{words[-1]}'). Check your source file.")
        sys.exit(1)
    for w in words:
        if not w.isascii() or not w.isalpha() or not w.islower():
            print(f"ERROR: word '{w}' is not plain lowercase ASCII - "
                  "the blob format assumes no embedded NUL/quote/backslash chars.")
            sys.exit(1)

    max_len = max(len(w) for w in words)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by generate_wordlist.py - do not hand-edit. */\n")
        f.write("#ifndef BIP39_WORDLIST_H\n#define BIP39_WORDLIST_H\n\n")
        f.write("#include <avr/pgmspace.h>\n\n")
        f.write("#define BIP39_WORD_COUNT 2048\n")
        f.write(f"#define BIP39_MAX_WORD_LEN {max_len}\n\n")
        f.write(
            "// All 2048 BIP39 English words packed back-to-back, each null-\n"
            "// terminated, in official wordlist order. Look up word N with\n"
            "// getWordAtIndex() in the main sketch - see that function for why.\n"
        )
        f.write("const char BIP39_WORDLIST_BLOB[] PROGMEM =\n")
        for i in range(0, len(words), WORDS_PER_LINE):
            chunk = words[i:i + WORDS_PER_LINE]
            literal = "".join(f"{w}\\0" for w in chunk)
            f.write(f'  "{literal}"\n')
        f.write("  ;\n\n#endif\n")

    print(f"Wrote {out_path} with {len(words)} words, max length {max_len}.")

if __name__ == "__main__":
    main()
