#!/usr/bin/env python3
"""
Generates bip39_wordlist.h from the official BIP39 English wordlist.

Usage:
    python3 generate_wordlist.py english.txt bip39_wordlist.h

Get english.txt from the official source:
    https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt
(Save the raw file locally - one word per line, 2048 lines total.)

The script verifies the list is the correct length and spot-checks the
first/last words against the spec before writing the header, so a
truncated or corrupted download will fail loudly instead of silently
producing a broken wordlist.
"""

import sys

def main():
    if len(sys.argv) != 3:
        print("Usage: python3 generate_wordlist.py <english.txt> <bip39_wordlist.h>")
        sys.exit(1)

    src_path, out_path = sys.argv[1], sys.argv[2]

    with open(src_path, "r", encoding="utf-8") as f:
        words = [line.strip() for line in f if line.strip()]

    if len(words) != 2048:
        print(f"ERROR: expected 2048 words, got {len(words)}. Check your source file.")
        sys.exit(1)
    if words[0] != "abandon" or words[-1] != "zoo":
        print("ERROR: wordlist doesn't match the expected BIP39 English list "
              f"(first='{words[0]}', last='{words[-1]}'). Check your source file.")
        sys.exit(1)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by generate_wordlist.py - do not hand-edit. */\n")
        f.write("#ifndef BIP39_WORDLIST_H\n#define BIP39_WORDLIST_H\n\n")
        f.write("#include <avr/pgmspace.h>\n\n")

        for i, word in enumerate(words):
            f.write(f'const char w{i:04d}[] PROGMEM = "{word}";\n')

        f.write("\nconst char* const BIP39_WORDLIST[] PROGMEM = {\n")
        for i in range(2048):
            comma = "," if i != 2047 else ""
            f.write(f"  w{i:04d}{comma}\n")
        f.write("};\n\n#endif\n")

    print(f"Wrote {out_path} with {len(words)} words.")

if __name__ == "__main__":
    main()
